name: CI

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{matrix.os}}
    if: "!contains(github.event.head_commit.message, '[skip build]')"
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            os_for_file_name: windows
            options: "-DVVCTRE_USE_BUNDLED_SDL2=ON -DUSE_DISCORD_PRESENCE=ON -DENABLE_MF=ON -DENABLE_FFMPEG_VIDEO_DUMPER=ON"
          - os: ubuntu-latest
            os_for_file_name: linux
            options: "-DUSE_DISCORD_PRESENCE=ON -DENABLE_FFMPEG_VIDEO_DUMPER=ON"
    steps:
      - name: Install Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install --yes libsdl2-dev libavcodec-dev libavformat-dev libswscale-dev
      - uses: actions/checkout@v1
      - run: git submodule update --init --recursive
      - name: Configure CMake
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release ${{matrix.options}}
      - name: Build
        working-directory: ./build
        shell: bash
        run: cmake --build . --config Release
      - name: Test
        working-directory: ./build
        run: ctest -C Release
      - name: Prepare to upload
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          cp README.md ./build/bin
          cp DEFAULT_CONTROLS.txt ./build/bin
          cp RPC.md ./build/bin
          cp license.txt ./build/bin
          if [ "$RUNNER_OS" == "Linux" ]; then
            rm ./build/bin/tests
          elif [ "$RUNNER_OS" == "Windows" ]; then
            rm ./build/bin/Release/tests.exe
            rm ./build/bin/Release/*.pdb
          fi
          export VERSION=${GITHUB_REF:10}
          echo ::set-env name=VERSION::$VERSION
          7z a vvctre-$VERSION-${{matrix.os_for_file_name}}.7z ./build/bin/*
      - name: Upload
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: vvctre-${{env.VERSION}}-${{matrix.os_for_file_name}}.7z
          asset_name: vvctre-${{env.VERSION}}-${{matrix.os_for_file_name}}.7z
          tag: ${{github.ref}}
          overwrite: true
      - name: Discord Notification
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          description: |
            vvctre ${{env.VERSION}} for ${{runner.os}} can now be downloaded from:
            https://github.com/${{github.repository}}/releases/tag/${{env.VERSION}}
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
